### ISSUE TITLE
settings issue

### ISSUE THREAD

**Issue by jjhesk** [jkwiecien/EasyImage#87] opened 2016-12-08 05:41 UTC
what kind of configuration should i be using when I need to pick an image from the camera folder and need to get the direct path with extension jpg? 

I did the similar thing but i only got 
file:/data/user/0/g.galaio.debug/cache/abc/27467da5-c62b-4003-a276-7efa02656d3d

which ending with the uuid code..

this is produced by
` String selected_name = selected_image_name.toURI().toString();`

i use 

```
        EasyImage.configuration(getActivity())
                .setImagesFolderName("abc")

                .saveInAppExternalFilesDir()
                .setCopyExistingPicturesToPublicLocation(false);

```

I am the same from #57

**Comment by jkwiecien** [comment] 2016-12-22 15:04
Duplicate of https://github.com/jkwiecien/EasyImage/issues/57

**Closed by jkwiecien** 2016-12-22 15:04 UTC
Labels: duplicate

**Comment by monowar1993** [comment] 2017-12-21 14:46
Do anyone found a way out?
