### ISSUE TITLE
merging providers

### ISSUE THREAD

**Issue by jjhesk** [jkwiecien/EasyImage#88] opened 2016-12-08 06:42 UTC
I have encountered this crash on merging tags

/app/src/main/AndroidManifest.xml:14:13-80 Error:
	Attribute provider#android.support.v4.content.FileProvider@authorities value=(g.galaio.debug.easyphotopicker.fileprovider) from [com.github.jkwiecien:EasyImage:1.4.1] AndroidManifest.xml:14:13-80
	is also present at [com.hkm.ui:image-picker:1.6.6] AndroidManifest.xml:31:13-70 value=(@string/shared_file_provider_hkm_ui).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:12:9-20:20 to override.

/app/src/main/AndroidManifest.xml:19:17-50 Error:
	Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/filepaths) from [com.github.jkwiecien:EasyImage:1.4.1] AndroidManifest.xml:19:17-50
	is also present at [com.hkm.ui:image-picker:1.6.6] AndroidManifest.xml:36:17-55 value=(@xml/provider_paths).
	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.

Do I need to merge the tag with meta-data with replace node? how to do so?

**Comment by Rajeshr34** [comment] 2016-12-22 14:30
+1 Same Issue

**Comment by jkwiecien** [comment] 2016-12-22 14:57
@rciovati could you have a look at this? Can we do something so the provider doesn't overlay other ppl stuff?

**Comment by rciovati** [comment] 2016-12-22 15:16
@jkwiecien  Yes, I could. 
@jjhesk @Rajeshr34 can you give me an hint on how reproduce the problem? It's not very clear to me how you end up having two providers with the very same authority.

**Comment by jkwiecien** [comment] 2016-12-22 15:45
@rciovati It's a duplicate of https://github.com/jkwiecien/EasyImage/issues/77 which can give you a hint

**Closed by jkwiecien** 2016-12-22 15:45 UTC
Labels: duplicate
