### ISSUE TITLE
java.lang.IllegalStateException: Unable to get the picture returned from camera

### ISSUE THREAD

**Issue by georgbachmann** [jkwiecien/EasyImage#83] opened 2016-11-21 15:33 UTC
I am trying to add images into my app. Picking from gallery works fine, but from Camera not. I always get a `java.lang.IllegalStateException: Unable to get the picture returned from camera` exception. I have sufficient permissions (`CAMERA, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE`) and also check for them!
Calling `EasyImage.openCamera(...)` opens the camera and I can take a picture, but then in `onActivityResult` I get the exception in `onImagePickerError`
Any idea?
I am testing on Android 7.0...

**Comment by jkwiecien** [comment] 2016-11-30 20:23
some stack trace?

**Comment by ValiDraganescu** [comment] 2016-12-08 11:48
`java.lang.IllegalStateException: Unable to get the picture returned from camera
12-08 13:39:10.936 12275-12275/com.* W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.onPictureReturnedFromCamera(EasyImage.java:389)
12-08 13:39:10.936 12275-12275/com.* W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.handleActivityResult(EasyImage.java:287)
12-08 13:39:10.936 12275-12275/* W/System.err:     at *.activity.CreateOrbActivity$override.onActivityResult(CreateOrbActivity.java:316)
12-08 13:39:10.936 12275-12275/* W/System.err:     at *activity.CreateOrbActivity$override.access$dispatch(CreateOrbActivity.java)
12-08 13:39:10.936 12275-12275/* W/System.err:     at *activity.CreateOrbActivity.onActivityResult(CreateOrbActivity.java:0)
12-08 13:39:10.936 12275-12275/* W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6917)
12-08 13:39:10.936 12275-12275/* W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
12-08 13:39:10.936 12275-12275/* W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
12-08 13:39:10.936 12275-12275/* W/System.err:     at android.app.ActivityThread.-wrap20(ActivityThread.java)
12-08 13:39:10.936 12275-12275/* W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
12-08 13:39:10.936 12275-12275/* W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-08 13:39:10.936 12275-12275/* W/System.err:     at android.os.Looper.loop(Looper.java:154)
12-08 13:39:10.936 12275-12275/* W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
12-08 13:39:10.936 12275-12275/* W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-08 13:39:10.937 12275-12275/* W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
12-08 13:39:10.937 12275-12275/* W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

Version 1.4.1, Android 7

**Comment by ValiDraganescu** [comment] 2016-12-08 13:26
In method takenCameraPicture the shared prefs map does not contain KEY_LAST_CAMERA_PHOTO

**Comment by ValiDraganescu** [comment] 2016-12-08 13:30
In createCameraPictureFile
` SharedPreferences.Editor editor = PreferenceManager.getDefaultSharedPreferences(context).edit();`
never gets to write the pref, when I attach the debugger and it gets to this line, the app crashes. Oddly enough, the app does not crash when not using the debugger.

And this happens only for taking image from camera but not from gallery.

**Comment by ValiDraganescu** [comment] 2016-12-08 13:43
So, in my manifest file, I had my own file provider and it looks that it was conflicting with the file provider from this library. I removed my file provider as it's not used anymore and now the library works as required on Android N. I don't use any other files than images so removing my provider solved the issue but I'm not sure what I need to do if I have to add support for other files in my app.

**Comment by jkwiecien** [comment] 2016-12-22 15:58
Duplicate of https://github.com/jkwiecien/EasyImage/issues/77

**Closed by jkwiecien** 2016-12-22 15:58 UTC
