### ISSUE TITLE
File extension name not coming properly

### ISSUE THREAD

**Issue by kprathap23** [jkwiecien/EasyImage#18] opened 2015-11-18 13:54 UTC
I try to select the images that i have selected previously or select image from EasyImage folder. sometimes the File extension is not coming.

               @Override
                public void onImagePicked(File imageFile, EasyImage.ImageSource source) {
                    //Handle the image
                    uploadToServer(imageFile);

                }

**Comment by ayushhgoyal** [comment] 2015-11-27 18:49
Yes it returns filepath without extension sometimes.

**Comment by emmgfx** [comment] 2016-01-21 19:23
No solutions to this issue? :(

**Comment by anantshah93** [comment] 2016-01-30 05:56
same problem

**Comment by jkwiecien** [comment] 2016-02-07 20:31
Duplicate of https://github.com/jkwiecien/EasyImage/issues/37 Questions there, check it out

**Closed by jkwiecien** 2016-02-07 20:31 UTC
Labels: duplicate
