### ISSUE TITLE
No limit on number of images selected

### ISSUE THREAD

**Issue by ChetanCul** [jkwiecien/EasyImage#106] opened 2017-02-17 06:13 UTC
I have implemented this library in an app, but I am getting some problem with low ram devices. When I select more images from gallery which are large in size the app crashes with following error

> E/PriorityExecutor: Request threw uncaught throwable java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 1944012 byte allocation with 523304 free bytes and 511KB until OOM

So it would be helpful if there is any way to limit the selection.
I know that it might not be easy to enforce selection limit while choosing images from external gallery like google photos, and I am not in favor of having a custom photo chooser activity by library as it will be able to display only local images and not those on the google cloud. So for now I am just taking first 10 images out of the chosen images and discarding the rest. I know this is not the best practice but can't help it yet.

So if there is any way to counter this then please help me here. 
Any help is appreciated.

**Comment by jkwiecien** [comment] 2017-11-03 11:31
Duplicate of: https://github.com/jkwiecien/EasyImage/issues/106

**Closed by jkwiecien** 2017-11-03 11:31 UTC

**Comment by computingfreak** [comment] 2018-04-11 05:40
Duplicate of #121 , (https://github.com/jkwiecien/EasyImage/issues/121)
