### ISSUE TITLE
Retain extension of image file

### ISSUE THREAD

**Issue by vytautasm** [jkwiecien/EasyImage#37] opened 2016-01-17 15:28 UTC
Hey, I really love this library!

One thing that is kind of bothering me is that the name of the image file that is being returned has no extension but only the UUID string like "2668b62b-ba73-4c3d-96e3-0e4174f43175". Would it be possible to retain the original extension like .jpg or .png?

**Comment by jkwiecien** [comment] 2016-02-07 20:31
When does this problem occur. Is it only when picking from camera, gallery or what?

**Comment by eggman87** [comment] 2016-03-11 17:35
I am seeing this with gallery pictures only. The file path is just the guid with no extension on it.

**Comment by apradanas** [comment] 2016-03-12 16:08
Hey @jkwiecien 
This issue happens only when picking from gallery. I suspect [EasyImageFiles::pickedExistingPicture](https://github.com/jkwiecien/EasyImage/blob/master/library/src/main/java/pl/aprilapps/easyphotopicker/EasyImageFiles.java#L88) is the cause, missing extension after random UDID. I hope this could help.

Thank you for this great library. I'm waiting for the update. Cheers!

**Comment by ikocijan** [comment] 2016-05-04 11:01
Hi,

is there any plan to push this fix to master?

**Comment by jkwiecien** [comment] 2016-05-05 10:04
Sorry for the absence. Merged the fix. Soon release.

**Closed by jkwiecien** 2016-05-05 10:05 UTC
Labels: bug
